### ISSUE TITLE
improve docs yaml preview

### ISSUE THREAD

**Issue by msramalho** [bellingcat/auto-archiver#206]
Things to improve:
1. add the steps configuration example, otherwise there's no place in the docs where the step name is easily visible
2. make sure this appears even when no configuration option is available, eg https://auto-archiver.readthedocs.io/en/latest/modules/autogen/enricher/meta_enricher.html `This module has no configuration options.`

in the above example it should be something like
```yaml
steps:
	enrichers:
		- meta_enricher
```

others would be 

```yaml
steps:
#...
	enrichers:
		- hash_enricher
# ...
hash_enricher:
	algorithm: "SHA-256"
# ...
```
I'm not sure whether to have the etc remarks so up to whoever implements this whether to keep the `#...`  or not
