### ISSUE TITLE
Whitelist and Blacklist of Worksheet

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#47]
We have a `spreadsheet` with multiple `worksheets` and I'd like to whitelist or blacklist based on the title. 

The reason is that one of the worksheets is an exact copy of the worksheet that I want archived, with the same column names. So the archiver picks it up when we don't want it.

I propose adding 2 extra config items, something like this:

```yaml
execution:
  # spreadsheet name - can be overwritten with CMD --sheet=
  sheet: "Test Hashing"

  # worksheet to blacklist. Leave blank which is default for none. Useful if users want a MASTERSHEET exact copy of the 
  # working worksheet
  worksheet_blacklist: MASTERSHEET
  # only check this worksheet rather than iterating through all worksheets in the spreadsheet. If whitelist is used 
  # then blacklist is ignored as whitelist is most restrictive.
  worksheet_whitelist: Sheet1
```

I only need a single items in the 'lists'. 

Happy to code this up and do a PR.
